### ISSUE TITLE
Description Errors

### ISSUE THREAD

**Issue by bedeoverend** [simplaio/docs#1]
Covering a few different issues:

### Controlling Data

Currently, they need to have a namespace at the root of the body, i.e. it doesn't default to the page it's on.

Should be either 'assign the right piece of content' or 'assign the right uid', rather than 'assign a piece of content'

### Custom namespaces:

UID's don't nest i.e. UID inside a namespace doesn't actually mean it's namespaced to that area i.e. you can't have:

```html
<simpla-namespace uid="one">
  <simpla-text uid="foo"></simpla-text>
</simpla-namespace>

<simpla-namespace uid="two">
  <simpla-text uid="foo"></simpla-text>
</simpla-namespace>
```

This is a future feature, but for now isn't supported

Also, when describing simpla-article, there's a type in the code snippet, says `simpla-artcile`

### Browser Support:

Doesn't really matter, but if you want to be finicky we're not polyfilling with Polymer, it's WebComponentsJS.

**Comment by seaneking** [comment]
For the record: 

- We'll just inject a root namespace during developer preview, as this is closer to the intended behaviour (body/html doc default namespace) than requiring the user to create their own namespace, which is an advanced use-case.

- We won't mention the namespace uid scoping and hope no-one notices during developer preview, but this should really be considered a bug - `<simpla-block>` should scope.

- Renaming `<simpla-namespace>` to `<simpla-block>`.

- Renaming `commands=""` to `tools=""`

- Removing all mentions of plaintext mode
