### ISSUE TITLE
Safari (iOS 9.3 iPad) docs don't scroll / #link causes blank page on refresh

### ISSUE THREAD

**Issue by stephenvoisey** [simplaio/docs#1]
Just a quick FYI, I found that the docs page falls over for me on my iPad. I can't scroll down to read them all. It seems to stop half way down the styling and selecting code section. Clicking the buttons doesn't do anything, but on a refresh, Safari will no longer display any content other than the nav.

The blank issue is resolved by removing the #start or other page link from the URL and reloading, but the inability to scroll all the content remains.

**Comment by seaneking** [comment]
@stephenvoisey assume you mean the docs at docs.simpla.io? Those are temporary and admittedly not great. Will be releasing these new docs on simpla.io soon.
